<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easyadmin.form.type' shared service.

include_once $this->targetDirs[3].'/vendor/javiereguiluz/easyadmin-bundle/src/Form/Type/Configurator/TypeConfiguratorInterface.php';
include_once $this->targetDirs[3].'/vendor/javiereguiluz/easyadmin-bundle/src/Form/Type/Configurator/AutocompleteTypeConfigurator.php';
include_once $this->targetDirs[3].'/vendor/javiereguiluz/easyadmin-bundle/src/Form/Type/Configurator/CollectionTypeConfigurator.php';
include_once $this->targetDirs[3].'/vendor/javiereguiluz/easyadmin-bundle/src/Form/Type/Configurator/CheckboxTypeConfigurator.php';
include_once $this->targetDirs[3].'/vendor/javiereguiluz/easyadmin-bundle/src/Form/Type/Configurator/TypeConfigurator.php';
include_once $this->targetDirs[3].'/vendor/javiereguiluz/easyadmin-bundle/src/Form/Type/Configurator/EntityTypeConfigurator.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/javiereguiluz/easyadmin-bundle/src/Form/Type/EasyAdminFormType.php';

$a = ${($_ = isset($this->services['easyadmin.config.manager']) ? $this->services['easyadmin.config.manager'] : $this->getEasyadmin_Config_ManagerService()) && false ?: '_'};

return $this->services['easyadmin.form.type'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\EasyAdminFormType($a, array(4 => new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\Configurator\AutocompleteTypeConfigurator(), 3 => new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\Configurator\CollectionTypeConfigurator(), 2 => new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\Configurator\CheckboxTypeConfigurator(), 1 => new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\Configurator\TypeConfigurator($a), 0 => new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\Configurator\EntityTypeConfigurator()));
