<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVwe8rzx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVwe8rzx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVwe8rzx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVwe8rzx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVwe8rzx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vwe8rzx',
    'container.build_id' => 'ee9f0c68',
    'container.build_time' => 1515684287,
));
