<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL01n6vd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL01n6vd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerL01n6vd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerL01n6vd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerL01n6vd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'L01n6vd',
    'container.build_id' => '00c30c47',
    'container.build_time' => 1516714701,
));
