<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8vkcjr8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8vkcjr8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8vkcjr8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8vkcjr8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8vkcjr8\appDevDebugProjectContainer(array(
    'container.build_hash' => '8vkcjr8',
    'container.build_id' => '2d687f6a',
    'container.build_time' => 1515656559,
));
